### PR TITLE
Fixes for user profile-pic in navbar and small screen ideafeed navigation

### LINKED ISSUE #103: Display user profile picture in navigation bar
The navigation bar should display the user's profile page on dropdown.

- Refer to [details.component.html](https://github.com/Cynthesize/cynthesize-frontend/blob/master/src/app/profile/user/details/details.component.html#L10) for use of profile picture. Currently we're also storing the user image link in the local storage. You should fetch the link/public id of the image and use that.

Refer to the screenshot for placement of image.
screenshot from 2019-02-11 18-49-19

### PR DESCRIPTION
**Pull request by prijeshb**
Fixes for issue #103 and #118 

ezgif com-crop

### CODE REVIEW

**Comment by WickedBrat** [comment]
@prijeshb A few check-lists:

- Please sign the CLA.
- Always give the title of you PR, something meaningful as this will be reflected in the commit history.
- You must **always** create two saperate pull requests for two different issues.

**Comment by prijeshb** [comment]
Ohk will take care of that !!

**Comment by prijeshb** [comment]
@WickedBrat should I revert or make new pull request?

**Comment by WickedBrat** [comment]
@prijeshb Create a new PR for this.

**Pull request merged**
